//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int QnID { get; set; }
        public string Qn { get; set; }
        public string ImageName { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public Nullable<int> Answer { get; set; }
        public Nullable<int> BUS1 { get; set; }
        public Nullable<int> SOF1 { get; set; }
        public Nullable<int> CS1 { get; set; }
        public Nullable<int> IOT1 { get; set; }
        public Nullable<int> BUS2 { get; set; }
        public Nullable<int> SOF2 { get; set; }
        public Nullable<int> CS2 { get; set; }
        public Nullable<int> IOT2 { get; set; }
    }
}
